package uk.gov.hmrc.cars.cleaner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.io.TempDir;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;
import uk.gov.hmrc.cleaner.model.ParsedDslEntry;
import uk.gov.hmrc.cleaner.strategy.*;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.*;

class DslParserTest {

    @TempDir
    Path tempDir;

    private Path mockDslFile;

    // Direct injection sources for Parameterized Loops
    static Stream<DslParsingStrategy> parsingStrategyProvider() {
        return Stream.of(new RegexDslParsingStrategy(), new DroolsDslParsingStrategy());
    }

    static Stream<DslDeletionStrategy> deletionStrategyProvider() {
        return Stream.of(new StructuralDeletionStrategy(), new RegexDeletionStrategy());
    }

    @BeforeEach
    void setUp() {
        mockDslFile = tempDir.resolve("validationResult-TEST.dsl");
    }

    // =========================================================================
    // PART 1: PARSING STRATEGY ASSERTERS
    // =========================================================================

    @ParameterizedTest
    @MethodSource("parsingStrategyProvider")
    void testStandardSingleLineExtraction(DslParsingStrategy strategy) throws IOException {
        String content = "[then]Emit validation error=setResult(\"ERR\");";
        Files.writeString(mockDslFile, content);

        List<ParsedDslEntry> entries = strategy.parse(mockDslFile);

        assertEquals(1, entries.size(), "Failed parsing on " + strategy.getClass().getSimpleName());
        assertEquals("Emit validation error", entries.get(0).plainTextToken().trim().replaceAll("\\s+", " "));
    }

    @ParameterizedTest
    @MethodSource("parsingStrategyProvider")
    void testWhitespaceNormalizationTokenization(DslParsingStrategy strategy) throws IOException {
        String content = "[then]Emit  double  spaces=setResult(\"ERR\");";
        Files.writeString(mockDslFile, content);

        List<ParsedDslEntry> entries = strategy.parse(mockDslFile);

        assertEquals(1, entries.size());
        // Both strategies normalize token spaces cleanly to ensure seamless matching inside the engine
        assertEquals("Emit double spaces", entries.get(0).plainTextToken().trim().replaceAll("\\s+", " "));
    }

    @ParameterizedTest
    @MethodSource("parsingStrategyProvider")
    void testMultiLineKeyExtraction(DslParsingStrategy strategy) throws IOException {
        String content = "[then]Emit validation error for\n" +
                         "    consignment shipment\n" +
                         "    consignor party name=setResult(\"ERR\");";
        Files.writeString(mockDslFile, content);

        List<ParsedDslEntry> entries = strategy.parse(mockDslFile);

        assertEquals(1, entries.size(), "Multi-line key extraction failed for " + strategy.getClass().getSimpleName());
        assertEquals("Emit validation error for consignment shipment consignor party name", 
                entries.get(0).plainTextToken().trim().replaceAll("\\s+", " "));
    }

    // =========================================================================
    // PART 2: DELETION STRATEGY ASSERTERS
    // =========================================================================

    @ParameterizedTest
    @MethodSource("deletionStrategyProvider")
    void testAtomicDeletionOfStandardRule(DslDeletionStrategy strategy) {
        String originalContent = "[then]Emit rule one=setResult(\"1\");\n" +
                                 "[then]Emit rule two=setResult(\"2\");";
        
        ParsedDslEntry targetEntry = new ParsedDslEntry(
                "[then]Emit rule one=setResult(\"1\");", "Emit rule one", 1);

        String result = strategy.deleteEntry(originalContent, targetEntry);

        assertFalse(result.contains("Emit rule one"), "Strategy " + strategy.getClass().getSimpleName() + " left the rule key behind.");
        assertFalse(result.contains("setResult(\"1\");"), "Strategy " + strategy.getClass().getSimpleName() + " left the action signature behind.");
        assertTrue(result.contains("[then]Emit rule two=setResult(\"2\");"), "Strategy accidentally damaged adjacent rules.");
    }

    @ParameterizedTest
    @MethodSource("deletionStrategyProvider")
    void testAtomicDeletionOfMultiLineKey(DslDeletionStrategy strategy) {
        String originalContent = "[then]Emit validation error for\n" +
                                 "    consignment shipment\n" +
                                 "    consignor party name=setResult(\"ERR\");\n" +
                                 "[then]Keep this adjacent rule=setResult(\"OK\");";

        // Simulated entry model generated by the parsers
        ParsedDslEntry targetEntry = new ParsedDslEntry(
                "", "Emit validation error for consignment shipment consignor party name", 1);

        String result = strategy.deleteEntry(originalContent, targetEntry);

        assertFalse(result.contains("consignment shipment"), "Failed to erase multi-line key fragment.");
        assertFalse(result.contains("setResult(\"ERR\");"), "Orphaned multi-line consequence action left behind.");
        assertFalse(result.contains("[then] \n"), "Left an orphaned dangling header tag.");
        assertTrue(result.contains("[then]Keep this adjacent rule=setResult(\"OK\");"), "Adjacent rule was corrupted.");
    }

    @ParameterizedTest
    @MethodSource("deletionStrategyProvider")
    void testAtomicDeletionOfMultiLineConsequenceAction(DslDeletionStrategy strategy) {
        // This simulates your production scenario where the right hand side drops across line breaks
        String originalContent = "[then]Target rule with multi line action=\n" +
                                 "    insert(emitter.emit(drools, BR092,\n" +
                                 "    of($cons, CONSIGNEE_PARTY_NAME)));\n" +
                                 "[then]Surviving standalone rule=setResult(\"SAFE\");";

        ParsedDslEntry targetEntry = new ParsedDslEntry(
                "", "Target rule with multi line action", 1);

        String result = strategy.deleteEntry(originalContent, targetEntry);

        assertFalse(result.contains("CONSIGNEE_PARTY_NAME"), "Failed to strip multi-line consequence block deep elements.");
        assertFalse(result.contains("insert(emitter.emit"), "Failed to strip multi-line action headers.");
        assertTrue(result.contains("[then]Surviving standalone rule=setResult(\"SAFE\");"), "Damaged surrounding code parameters.");
    }
}